### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrayson** [TIDE-ITRH/speccy#1]
- [x] package layout document with list of modules and functions within each one @astfalckl 
- [x] periodogram function w/ window
- [x] dwhittle
- [x] add tapering to all existing functions
- [x] random sampling functions
- [ ] add Toeplitz tricks to Gaussian sampling
- [x] fix delta in aliasing function
- [x] make everything 2-sided from the start
- [ ] #5
- [ ] ...

**Comment by iosonobert** [comment]
Did you forget to commit something here?
